src/Portfolio/LaureBundle/Form/ImageType.php
<?php

namespace Portfolio\LaureBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ImageType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('file')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Portfolio\LaureBundle\Entity\Image'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'portfolio_laurebundle_image';
    }
}

src/Portfolio/LaureBundle/Controller/AboutController.php
<?php

namespace Portfolio\LaureBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class AboutController extends Controller
{
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $aboutIntro = $em->getRepository('PortfolioLaureBundle:AboutIntro')->findAll();
        $aboutFeelings = $em->getRepository('PortfolioLaureBundle:AboutFeeling')->findBy(
            array(),
            array('createdAt' => 'ASC')
        );

        return $this->render('PortfolioLaureBundle:About:index.html.twig',
            array(
                'aboutIntro' => $aboutIntro[0],
                'aboutFeelings' => $aboutFeelings
            ));
    }
} 

src/Portfolio/LaureBundle/Resources/views/About/index.html.twig
<div class="row">
    <h2>ABOUT</h2>
    <p>{{ aboutIntro.text|nl2br }}</p>
    {% if aboutFeelings is not empty %}
        <div class="circle-content">
            {% for aboutFeeling in aboutFeelings %}
                <div class="circle"
                     style="border: 10px solid {{ aboutFeeling.color }};">
                    <div class="flex">
                        <p>{{ aboutFeeling.percentage }}<span>%</span><br />
                            <span>{{ aboutFeeling.name|capitalize }}</span></p>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>